---
name-template: "Release v$RESOLVED_VERSION"
tag-template: "v$RESOLVED_VERSION"
change-template: "- $TITLE @$AUTHOR (#$NUMBER)"
change-title-escapes: '\<*_&'
categories:
  - title: "Community Contributions"
    labels: ["community"]
  - title: "Kubernetes"
    labels: ["area/kubernetes", "renovate/helm"]
  - title: "Github"
    labels: ["area/github", "renovate/github-action", "renovate/github-release"]
  - title: "Ansible"
    labels: ["area/ansible", "renovate/ansible"]
  - title: "Terraform"
    labels: ["area/terraform", "renovate/terraform"]
  - title: "Maintenance"
    labels: ["docs"]
  - title: "Container"
    labels: ["area/container", "renovate/container"]
version-resolver:
  major:
    labels: ["type/break"]
  minor:
    labels: ["type/major", "type/minor"]
  patch:
    labels: ["type/patch"]
  default: patch
template: |
  ## What's Changed

  $CHANGES

  **Full Changelog**: https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...v$RESOLVED_VERSION
